default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: postgres
  password: 2000

development:
  <<: *default
  database: hello_app

test:
  <<: *default
  database: hello_app_test

production:
  <<: *default
  database: hello_app_production